export const START_DISCOVERY = 'START_DISCOVERY'
export const ERROR_DISCOVERY = 'ERROR_DISCOVERY'
export const END_DISCOVERY = 'END_DISCOVERY'

export const SET_START_DISCOVERY_TIME = 'START_DISCOVERY_TIME'
export const SET_END_DISCOVERY_TIME = 'END_DISCOVERY_TIME'

export const DEVICE_DISCOVERED = 'DEVICE_DISCOVERED'
export const ZSERVICE_DISCOVERED = 'ZSERVICE_DISCOVERED';
